language: python
# command to install dependencies
install: "pip install 'virtualenv<1.10' -e . detox"
# # command to run tests
script: detox --recreate
notifications:
  irc:
    - "chat.freenode.net#pytest-dev"
  email:
    - pytest-commit@python.org
